name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Staging

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to ACR
        run: |
          az acr login --name aakankshaacr03100007

      - name: Build and push Docker image
        run: |
          IMAGE=aakankshaacr03100007.azurecr.io/kube-gallery:${{ github.sha }}
          echo "Using image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Azure Container Apps (Staging)
        run: |
          az containerapp update \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            -n aca-frontend-staging \
            --image $IMAGE