name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to ACR
        run: |
          REG_NAME=$(echo ${{ secrets.AZURE_CONTAINER_REGISTRY }} | cut -d'.' -f1)
          az acr login --name $REG_NAME

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.AZURE_CONTAINER_REGISTRY }}/kube-gallery:${{ github.sha }}
          echo "Using image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Azure Container Apps (Production)
        run: |
          az containerapp update \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            -n aca-frontend-production \
            --image $IMAGE
            