name: Deploy to Staging

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/kube-gallery:${{ github.sha }}
          echo "Using image: $IMAGE"
          docker build -t $IMAGE .
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Azure Container Apps (Staging)
        run: |
          az containerapp update \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            -n aca-frontend-staging \
            --image $IMAGE