name: Deploy to Azure Container Apps (Staging)

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read    # so actions/checkout works

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/kube-gallery:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Azure Container App (Staging)
        run: |
          az containerapp update \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            -n aca-frontend-staging \
            --image $IMAGE