name: image-security-scan
on:
  pull_request:
    branches: [ main, master ]

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Build the image that we will scan
      - name: Build image
        run: docker build -t pr-kubegallery:${{ github.sha }} .

      # Run Docker Scout via the official GitHub Action, limited to High+Critical
      - name: Docker Scout CVEs (High/Critical only)
        uses: docker/scout-action@v1
        with:
          command: cves
          image: pr-kubegallery:${{ github.sha }}
          only-severities: critical,high
          exit-code: true   # fail the job if any High/Critical exists
